[versions]
junit-jupiter-version = "5.10.2"
lombok-version = "1.18.32"
guava-version = "33.1.0-jre"
springboot-version = "3.2.3"
springframework-version = "6.1.4"
mockito-version = "5.7.0"
spring-dependency-version = "1.1.4"
jacoco-version = "0.8.11"
slf4j-version= "2.1.0-alpha1"
maven-compiler-plugin-version="3.11.0"

# Kafka Consumer
avro-version="1.11.3"
spring-kafka-version="3.0.12"

#Kafka Publisher
kafka-avro-serializer-version="7.5.1"

#Lg5 Code Quality
maven-checkstyle-plugin-version="3.3.0"
puppycrawl-tools-checkstyle-version="10.12.1"

# build images Jib
jib-maven-plugin-version ="3.4.0"



[libraries]
# spring boot
springboot-parent = { group = "org.springframework.boot", name = "spring-boot-starter-parent", version.ref = "springboot-version" }
springboot-dependencies = { group = "org.springframework.boot", name = "spring-boot-dependencies", version.ref = "springboot-version" }
springboot-starter = { group = "org.springframework.boot", name = "spring-boot-starter", version.ref = "springboot-version" }
springboot-json = { group = "org.springframework.boot", name = "spring-boot-starter-json", version.ref = "springboot-version" }
springboot-devtools = { group = "org.springframework.boot", name = "spring-boot-devtools", version.ref = "springboot-version" }
springboot-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation", version.ref = "springboot-version" }

#Spring
spring-tx = { group = "org.springframework", name = "spring-tx", version.ref = "springframework-version" }
spring-context = { group = "org.springframework", name = "spring-context", version.ref = "springframework-version" }

# Logger
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j-version" }
springboot-logging = { group = "org.springframework.boot", name = "spring-boot-starter-logging", version.ref = "springboot-version" }

# Test
springboot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test", version.ref = "springboot-version" }

jupiter-root = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter-version" }
jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit-jupiter-version" }
jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit-jupiter-version" }
jupiter-launcher = { module = "org.junit.platform:junit-platform-launcher" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito-version" }

# Utils
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok-version" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava-version" }

#events
spring-kafka = { group = "org.springframework.kafka", name = "spring-kafka", version.ref = "spring-kafka-version" }
apache-avro = { group = "org.apache.avro", name = "avro", version.ref = "avro-version" }
avro-plugin = { group = "org.apache.avro", name = "avro-maven-plugin", version.ref = "avro-version" }
kafka-avro-serializer = { group = "io.confluent", name = "kafka-avro-serializer", version.ref = "kafka-avro-serializer-version" }

# code qualities
checkstyle-plugin = { group = "org.apache.maven.plugins", name = "maven-checkstyle-plugin", version.ref = "maven-checkstyle-plugin-version" }
puppycrawl-tools = { group = "com.puppycrawl.tools", name = "checkstyle", version.ref = "puppycrawl-tools-checkstyle-version" }

# build images with JIB
jib-plugin = { group = "com.google.cloud.tools", name = "jib-maven-plugin", version.ref = "jib-maven-plugin-version" }


[plugins]
springboot-plugin = { id = "org.springframework.boot", version.ref = "springboot-version" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-version" }
