[versions]
junit-jupiter-version = "5.10.2"
lombok-version = "1.18.32"
guava-version = "33.1.0-jre"
springboot-version = "3.2.3"
mockito-version = "5.7.0"
spring-dependency-version = "1.1.4"
jacoco-version = "0.8.11"
slf4j-version= "2.1.0-alpha1"
maven-compiler-plugin-version="3.11.0"



[libraries]
# spring boot
springboot-parent = { group = "org.springframework.boot", name = "spring-boot-starter-parent", version.ref = "springboot-version" }
springboot-dependencies = { group = "org.springframework.boot", name = "spring-boot-dependencies", version.ref = "springboot-version" }
springboot-starter = { group = "org.springframework.boot", name = "spring-boot-starter", version.ref = "springboot-version" }


springboot-logging = { group = "org.springframework.boot", name = "spring-boot-starter-logging", version.ref = "springboot-version" }

# Test
springboot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test", version.ref = "springboot-version" }

jupiter-root = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter-version" }
jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit-jupiter-version" }
jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit-jupiter-version" }
jupiter-launcher = { module = "org.junit.platform:junit-platform-launcher" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito-version" }



# Utils
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok-version" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava-version" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j-version" }

[plugins]
springboot-plugin = { id = "org.springframework.boot", version.ref = "springboot-version" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-version" }
