[versions]
junit-jupiter-version = "5.9.2"
lombok-version = "1.18.16"
guava-version = "31.0.1-jre"
spring-boot-version = "3.2.3"
mockito-version = "5.7.0"



[libraries]
# spring boot
springboot-starter-parent = { group = "org.springframework.boot", name = "springboot-starter-parent", version.ref = "spring-boot-version" }
springboot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test", version.ref = "spring-boot-version" }


# Test

jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter-version" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito-version" }

# Utils
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok-version" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava-version" }
