[versions]
junit-jupiter-version = "5.10.2"
lombok-version = "1.18.32"
guava-version = "31.0.1-jre"
spring-boot-version = "3.2.3"
mockito-version = "5.7.0"
puppycrawl-version = "10.12.1"



[libraries]
# spring boot
springboot-starter-parent = { group = "org.springframework.boot", name = "springboot-starter-parent", version.ref = "spring-boot-version" }
springboot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test", version.ref = "spring-boot-version" }

springboot-logging = { group = "org.springframework.boot", name = "spring-boot-starter-logging", version.ref = "spring-boot-version" }

# Test

jupiter-root = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter-version" }
jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit-jupiter-version" }
jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit-jupiter-version" }
jupiter-launcher = { module="org.junit.platform:junit-platform-launcher"}
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito-version" }

# Checkstyle
puppycrawl-tools = { group = "com.puppycrawl.tools", name = "checkstyle", version.ref = "puppycrawl-version" }

# Utils
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok-version" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava-version" }
